name: MoakCasey IAC - Display Branch Name

on:
  push:
    branches:
      - main

jobs:
  display-branch-name:
    name: Display Branch Name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Display branch name
        run: |
          echo "Branch Name: $BRANCH_NAME"
